data: './data/'
logF: 'experiments/story/'
epoch: 25
batch_size: 32
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
learning_rate: 0.0003
max_grad_norm: 5
learning_rate_decay: 0.8
start_decay_at: 6
emb_size: 256
hidden_size: 512
dec_num_layers: 1
enc_num_layers: 1
bidirectional: True
dropout: 0.5
max_time_step: 50
eval_interval: 2000
save_interval: 1000
metrics: ['bleu']
shared_vocab: True
beam_size: 1
unk: True
schedule: False
selfatt: True
schesamp: False
swish: True
length_norm: True